---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weaviate-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weaviate
  template:
    metadata:
      labels:
        app: weaviate
    spec:
      containers:
        - name: weaviate
          image: semitechnologies/weaviate:latest
          ports:
            - containerPort: 8080
          env:
            - name: AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED
              value: 'true'
            - name: PERSISTENCE_DATA_PATH
              value: /var/lib/weaviate
            - name: DEFAULT_VECTORIZER_MODULE
              value: none
            - name: ENABLE_MODULES
              value: ''
---
apiVersion: v1
kind: Service
metadata:
  name: weaviate-service
spec:
  selector:
    app: weaviate
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
